### ISSUE TITLE
http proxy (default use system proxy)

### ISSUE THREAD

**Issue by hcy42003** [WayneJz/teslamate-addr-fix#11]
我用的是docker安装teslamate， linux下代理的监听端口是127.0.0.1:1070 ， 在linux下运行了teslamate-addr-fix 默认脚本，脚本执行成功，但是还是无法访问地图，这个代理怎么设置，怎么改呢？

**Comment by hcy42003** [comment]
运行 
./teslamate-addr-fix -password secret -proxy http://172.17.0.1:1070
没有任何报错和提示
log文件也是 0kb

**Comment by WayneJz** [comment]
> 运行 ./teslamate-addr-fix -password secret -proxy http://172.17.0.1:1070 没有任何报错和提示 log文件也是 0kb

没log应该是扫描完成，没有可修复的数据，你的 drive graph 应该地址都是全的了吧？
无法访问地图这个，这还得你工作电脑上的浏览器（不是 NAS）上有配置代理，因为 grafana 是前端访问的 openstreetmap

**Comment by hcy42003** [comment]
> > 运行 ./teslamate-addr-fix -password secret -proxy http://172.17.0.1:1070 没有任何报错和提示 log文件也是 0kb
> 
> 没log应该是扫描完成，没有可修复的数据，你的 drive graph 应该地址都是全的了吧？ 无法访问地图这个，这还得你工作电脑上的浏览器（不是 NAS）上有配置代理，因为 grafana 是前端访问的 openstreetmap

对，懂了
