### ISSUE TITLE
Bad Request

### ISSUE THREAD

**Issue by dylanchou66** [WayneJz/teslamate-addr-fix#13]
这个原因是数据库记录的值为0的原因么？
日志文件如下：
2023/04/27 04:52:40 psql_client.go:193: get address from osm failed, lat=0, lon=0, err=Get "https://nominatim.openstreetmap.org/reverse?lat=0.000000&lon=0.000000&format=json": Bad Request
2023/04/27 04:52:40 psql_client.go:193: get address from osm failed, lat=0, lon=0, err=Get "https://nominatim.openstreetmap.org/reverse?lat=0.000000&lon=0.000000&format=json": Bad Request
2023/04/27 04:52:40 psql_client.go:193: get address from osm failed, lat=0, lon=0, err=Get "https://nominatim.openstreetmap.org/reverse?lat=0.000000&lon=0.000000&format=json": Bad Request
2023/04/27 04:52:40 psql_client.go:193: get address from osm failed, lat=0, lon=0, err=Get "https://nominatim.openstreetmap.org/reverse?lat=0.000000&lon=0.000000&format=json": Bad Request

**Comment by WayneJz** [comment]
> 这个原因是数据库记录的值为0的原因么？ 日志文件如下： 2023/04/27 04:52:40 psql_client.go:193: get address from osm failed, lat=0, lon=0, err=Get "https://nominatim.openstreetmap.org/reverse?lat=0.000000&lon=0.000000&format=json": Bad Request 2023/04/27 04:52:40 psql_client.go:193: get address from osm failed, lat=0, lon=0, err=Get "https://nominatim.openstreetmap.org/reverse?lat=0.000000&lon=0.000000&format=json": Bad Request 2023/04/27 04:52:40 psql_client.go:193: get address from osm failed, lat=0, lon=0, err=Get "https://nominatim.openstreetmap.org/reverse?lat=0.000000&lon=0.000000&format=json": Bad Request 2023/04/27 04:52:40 psql_client.go:193: get address from osm failed, lat=0, lon=0, err=Get "https://nominatim.openstreetmap.org/reverse?lat=0.000000&lon=0.000000&format=json": Bad Request

常见问题，少数情况下 Tesla API 获取到的地址就是空，对于这种的只能忽略了
