### ISSUE TITLE
请求的内容太多，好像被屏蔽了，应该如何解决？

### ISSUE THREAD

**Issue by cupid0426** [WayneJz/teslamate-addr-fix#14]
<body>
<h1>Access blocked</h1>

<p>You have been blocked because you have violated the
<a href="https://operations.osmfoundation.org/policies/nominatim/">usage policy</a>
of OSM's Nominatim geocoding service. Please be aware that OSM's resources are
limited and shared between many users. The usage policy is there to ensure that
the service remains usable for everybody.</p>

<p>Please review the terms and make sure that your
software adheres to the terms. You should in particular verify that you have set a
<b>custom HTTP referrer or HTTP user agent</b> that identifies your application, and
that you are not overusing the service with massive bulk requests.</p>

<p>If you feel that this block is unjustified or remains after you have adopted
your usage, you may contact the Nominatim system administrator at
nominatim@openstreetmap.org to have this block lifted.</p>
</body>
</head>

因为刚装上，想解决看不到历史的问题，等了半天，发现地址信息还是空的，然后就在服务器上请求了一下，日志中的查询地址，结果发现被屏蔽了，这个问题应该如何解决？因为teslamate装了差不多两年了，是不是我没有地址信息的数据太多了？

部分日志：
2023/06/28 13:07:56 /Users/jiangzhou/SDK/gopath/pkg/mod/gorm.io/gorm@v1.24.1-0.20221019064659-5dd2bb482755/callbacks.go:134 record not found
[0.155ms] [rows:0] SELECT * FROM "positions" WHERE id = 0 ORDER BY "positions"."id" LIMIT 1

2023/06/28 13:07:56 /Users/jiangzhou/SDK/gopath/pkg/mod/gorm.io/gorm@v1.24.1-0.20221019064659-5dd2bb482755/callbacks.go:134 record not found
[0.140ms] [rows:0] SELECT * FROM "positions" WHERE id = 0 ORDER BY "positions"."id" LIMIT 1

2023/06/28 13:07:56 /Users/jiangzhou/SDK/gopath/pkg/mod/gorm.io/gorm@v1.24.1-0.20221019064659-5dd2bb482755/callbacks.go:134 record not found
[0.275ms] [rows:0] SELECT * FROM "positions" WHERE id = 0 ORDER BY "positions"."id" LIMIT 1

2023/06/28 13:07:56 /Users/jiangzhou/SDK/gopath/pkg/mod/gorm.io/gorm@v1.24.1-0.20221019064659-5dd2bb482755/callbacks.go:134 record not found
[0.187ms] [rows:0] SELECT * FROM "positions" WHERE id = 0 ORDER BY "positions"."id" LIMIT 1

2023/06/28 13:07:56 /Users/jiangzhou/SDK/gopath/pkg/mod/gorm.io/gorm@v1.24.1-0.20221019064659-5dd2bb482755/callbacks.go:134 record not found
[0.270ms] [rows:0] SELECT * FROM "positions" WHERE id = 0 ORDER BY "positions"."id" LIMIT 1

2023/06/28 13:07:57 /Users/jiangzhou/SDK/gopath/pkg/mod/gorm.io/gorm@v1.24.1-0.20221019064659-5dd2bb482755/callbacks.go:134 record not found
[0.245ms] [rows:0] SELECT * FROM "positions" WHERE id = 0 ORDER BY "positions"."id" LIMIT 1

2023/06/28 13:07:57 /Users/jiangzhou/SDK/gopath/pkg/mod/gorm.io/gorm@v1.24.1-0.20221019064659-5dd2bb482755/callbacks.go:134 record not found
[0.309ms] [rows:0] SELECT * FROM "positions" WHERE id = 0 ORDER BY "positions"."id" LIMIT 1

**Comment by cupid0426** [comment]
请求作者修改每条地址查询请求的间隔时间为1分钟或更长，因为openstreetmap网站已经明确写出了，查询间隔为1分钟，如果一次请求内容太多，会导致代理ip被禁用无法使用。

**Comment by WayneJz** [comment]
> 请求作者修改每条地址查询请求的间隔时间为1分钟或更长，因为openstreetmap网站已经明确写出了，查询间隔为1分钟，如果一次请求内容太多，会导致代理ip被禁用无法使用。

看您之前发的日志，似乎没有调用OSM网站被禁用的报错。
有记录类似 osm returns error status, status=xxx, url=xxx 的日志吗？这个是调用OSM网站报错的日志
有的话可以提供一下

**Comment by cupid0426** [comment]
> > 请求作者修改每条地址查询请求的间隔时间为1分钟或更长，因为openstreetmap网站已经明确写出了，查询间隔为1分钟，如果一次请求内容太多，会导致代理ip被禁用无法使用。
> 
> 看您之前发的日志，似乎没有调用OSM网站被禁用的报错。 有记录类似 osm returns error status, status=xxx, url=xxx 的日志吗？这个是调用OSM网站报错的日志 有的话可以提供一下

兄弟乌龙了，功能正常，这几天已经运行正常了，都已经有地址信息了。谢了。
