### ISSUE TITLE
关于使用方法

### ISSUE THREAD

**Issue by Liuxianguang1986** [WayneJz/teslamate-addr-fix#2]
您好，
感谢您提供的的程序。有几个问题请教，

1、如果用docker安装的teslamate，系统开启代理也可以访问openstreet了，但是为什么还是docker日志里还是timeout呢？
2、我看您有说暴露pg database端口，没有想明白什么原理请指教
3、关于修复程序是否和官方手工修复程序是一个原理

**Comment by Lengran1992** [comment]
container不能直接访问宿主机网络

**Comment by Liuxianguang1986** [comment]
> 
了解了，你现在是怎么解决的，试了一下传env传https_proxy也不行

**Comment by WayneJz** [comment]
> > 
> 
> 了解了，你现在是怎么解决的，试了一下传env传https_proxy也不行

可能代理没有开启/填错了，试试 `lsof -i:7890` (7890改为你代理的端口），看有没有输出

**Comment by Liuxianguang1986** [comment]
> lsof -i:7890
 ssh进container，env可以看到clash代理地址，teslamate就可以走代理吗？我看日志里还有timeout无法访问

**Comment by Liuxianguang1986** [comment]
> 



> > > 
> > 
> > 
> > 了解了，你现在是怎么解决的，试了一下传env传https_proxy也不行
> 
> 可能代理没有开启/填错了，试试 `lsof -i:7890` (7890改为你代理的端口），看有没有输出

lsof -i:7890
ssh进container，env可以看到clash代理地址，teslamate就可以走代理吗？我看日志里还有timeout无法访问

**Comment by Liuxianguang1986** [comment]
@WayneJz 执行时候报错 ./teslamate-addr-fix: line 8: syntax error near unexpected token `newline'
./teslamate-addr-fix: line 8: `<!DOCTYPE html>'

**Comment by WayneJz** [comment]
> @WayneJz 执行时候报错 ./teslamate-addr-fix: line 8: syntax error near unexpected token `newline' ./teslamate-addr-fix: line 8: `'

这个问题应该是你下错文件了，下对应系统的二进制。

然后上一个问题，不太清楚你是怎么部署的？这个工具和teslamate主程序无关，工具只读写了teslamate-database，属于第三方的修复。所以teslamate主程序里面有timeout是正常情况，这个要等teslamate的作者修复。

这个工具需要运行在宿主机环境，不支持在容器里用。

**Comment by wombat-toy** [comment]
没有代理HTTP的我，看来只能放弃地址显示这个功能了，如果有人能把地图替换成国内的地图就好了。而且我是部署在nas上的……
