### ISSUE TITLE
你好，我是极空间nsa的docker,能加微信具体请教下怎么部署吗？

### ISSUE THREAD

**Issue by QinChBeSt** [WayneJz/teslamate-addr-fix#5]
WX:qinchbest

**Comment by roderickbao** [comment]
./teslamate-addr-fix -password secret -proxy http://ip:port

**Comment by QinChBeSt** [comment]
> ./teslamate-addr-fix -password secret -proxy http://ip:port

这句话加在哪？

**Comment by roderickbao** [comment]
这是单次运行的命令，想要定期自动运行请使用crontab
