### ISSUE TITLE
数据库操作报错了

### ISSUE THREAD

**Issue by MNZhu** [WayneJz/teslamate-addr-fix#6]
2022/12/02 15:05:03 start position not found, id=0, drive=&{ID:1344 StartPositionID:0 EndPositionID:0 StartAddressID:0 EndAddressID:0}

**Comment by WayneJz** [comment]
> 2022/12/02 15:05:03 start position not found, id=0, drive=&{ID:1344 StartPositionID:0 EndPositionID:0 StartAddressID:0 EndAddressID:0}

这个是 teslamate 拉回来的数据就没有存 startPositionID （起始位置ID），可以忽略掉这条报错，程序也是作忽略处理的
