### ISSUE TITLE
请问 log有这个错误 如何处理？

### ISSUE THREAD

**Issue by commandent** [WayneJz/teslamate-addr-fix#7]
2022/12/07 14:41:23 get address from osm failed, lat=19.913121, lon=110.316397, err=&url.Error{Op:"Get", URL:"https://nominatim.openstreetmap.org/reverse?lat=19.913121&lon=110.316397&format=json", Err:(*net.OpError)(0xc00025b270)}

**Comment by WayneJz** [comment]
应该是网络代理没有配置好，在你运行环境试一下：

`curl -v 'https://nominatim.openstreetmap.org/reverse?lat=19.913121&lon=110.316397&format=json'` 

看有没有报错

**Comment by commandent** [comment]
> 应该是网络代理没有配置好，在你运行环境试一下：
> 
> `curl -v 'https://nominatim.openstreetmap.org/reverse?lat=19.913121&lon=110.316397&format=json'`
> 
> 看有没有报错

**国内IP 访问 不可达。**    

用香港的IP 才行， 不知道这个 有什么办法解决 ？谢谢了


root@bogon bin]# curl -v 'https://nominatim.openstreetmap.org/reverse?lat=19.913121&lon=110.316397&format=json'
* About to connect() to nominatim.openstreetmap.org port 443 (#0)
*   Trying 199.96.58.105...



* 连接超时
*   Trying 2001::3257:5df6...
* Failed to connect to 2001::3257:5df6: 网络不可达
* Failed connect to nominatim.openstreetmap.org:443; 网络不可达
* Closing connection 0
curl: (7) Failed to connect to 2001::3257:5df6: 网络不可达

**Comment by WayneJz** [comment]
> > 应该是网络代理没有配置好，在你运行环境试一下：
> > `curl -v 'https://nominatim.openstreetmap.org/reverse?lat=19.913121&lon=110.316397&format=json'`
> > 看有没有报错
> 
> **国内IP 访问 不可达。**
> 
> 用香港的IP 才行， 不知道这个 有什么办法解决 ？谢谢了
> 
> root@bogon bin]# curl -v 'https://nominatim.openstreetmap.org/reverse?lat=19.913121&lon=110.316397&format=json'
> 
> * About to connect() to nominatim.openstreetmap.org port 443 (#0)
> * Trying 199.96.58.105...
> * 连接超时
> * Trying 2001::3257:5df6...
> * Failed to connect to 2001::3257:5df6: 网络不可达
> * Failed connect to nominatim.openstreetmap.org:443; 网络不可达
> * Closing connection 0
>   curl: (7) Failed to connect to 2001::3257:5df6: 网络不可达

国内对这个网站是封禁了，得按照文档里设置下 HTTP 代理
