### ISSUE TITLE
报错了，这是怎么回事儿？

### ISSUE THREAD

**Issue by bawfnje** [WayneJz/teslamate-addr-fix#8]
2022/12/11 13:59:55 /Users/jiangzhou/SDK/gopath/pkg/mod/gorm.io/gorm@v1.24.1-0.20221019064659-5dd2bb482755/callbacks.go:134 record not found
[0.640ms] [rows:0] SELECT * FROM "positions" WHERE id = 0 ORDER BY "positions"."id" LIMIT 1

**Comment by Nightmare0079** [comment]
码  +1

**Comment by WayneJz** [comment]
这个应该不需要处理。原因是 teslamate 底层数据就没有拉到位置信息（可能是拉取的时候车上4G信号弱），程序上也是忽略这个错误的。
